/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Changing user password */
        put: operations["auth_change_password_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Changing user password */
        patch: operations["auth_change_password_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login for user */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logout user */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve and update User Profile */
        get: operations["auth_profile_retrieve"];
        /** @description Retrieve and update User Profile */
        put: operations["auth_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Retrieve and update User Profile */
        patch: operations["auth_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registration for new user */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listing and creating comments */
        get: operations["comments_list"];
        put?: never;
        /** @description Listing and creating comments */
        post: operations["comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}/replies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET comment`s replies */
        get: operations["comments_replies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detail view for retrieve, update, and delete comment */
        get: operations["comments_retrieve"];
        /** @description Detail view for retrieve, update, and delete comment */
        put: operations["comments_update"];
        post?: never;
        /** @description Detail view for retrieve, update, and delete comment */
        delete: operations["comments_destroy"];
        options?: never;
        head?: never;
        /** @description Detail view for retrieve, update, and delete comment */
        patch: operations["comments_partial_update"];
        trace?: never;
    };
    "/api/v1/comments/my-comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Comments of current user */
        get: operations["comments_my_comments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/post/{post_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET comments of certain post */
        get: operations["comments_post_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["docs_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List of user payments. */
        get: operations["payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel payment for current user. */
        post: operations["payments_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/refund/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create new refund for payment. */
        post: operations["payments_refund_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/retry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Retry payment. */
        post: operations["payments_retry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check payment status of current user. */
        get: operations["payments_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detail information about a payment. */
        get: operations["payments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/analytics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Analytic of payment for administrators only. */
        get: operations["payments_analytics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/create-checkout-session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create Stripe Checkout session of subscription payment. */
        post: operations["payments_create_checkout_session_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description History of payment history for current user. */
        get: operations["payments_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/refunds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List of refunds for administrators only. */
        get: operations["payments_refunds_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/refunds/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detail information about a refund. */
        get: operations["payments_refunds_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Api endpoint for listing and creating Posts with support for pinned posts.
         *     Pinned posts displayed first in "pinned_at" order.
         */
        get: operations["posts_list"];
        put?: never;
        /**
         * @description Api endpoint for listing and creating Posts with support for pinned posts.
         *     Pinned posts displayed first in "pinned_at" order.
         */
        post: operations["posts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Api endpoint for concrete post */
        get: operations["posts_retrieve"];
        /** @description Api endpoint for concrete post */
        put: operations["posts_update"];
        post?: never;
        /** @description Api endpoint for concrete post */
        delete: operations["posts_destroy"];
        options?: never;
        head?: never;
        /** @description Api endpoint for concrete post */
        patch: operations["posts_partial_update"];
        trace?: never;
    };
    "/api/v1/posts/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Api endpoint for listing and creating Categories */
        get: operations["posts_categories_list"];
        put?: never;
        /** @description Api endpoint for listing and creating Categories */
        post: operations["posts_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/categories/{category_slug}/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Posts for defined category */
        get: operations["posts_categories_posts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Api endpoint for concrete category */
        get: operations["posts_categories_retrieve"];
        /** @description Api endpoint for concrete category */
        put: operations["posts_categories_update"];
        post?: never;
        /** @description Api endpoint for concrete category */
        delete: operations["posts_categories_destroy"];
        options?: never;
        head?: never;
        /** @description Api endpoint for concrete category */
        patch: operations["posts_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/posts/featured/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Recommended posts for main page:
         *     - Pinned posts (3 max)
         *     - Popular posts for last week
         */
        get: operations["posts_featured_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/my-posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Api endpoint for listing current user's posts */
        get: operations["posts_my_posts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/pinned/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return pinned posts */
        get: operations["posts_pinned_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/popular/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 10 most popular Posts */
        get: operations["posts_popular_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/recent/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 10 most recent Posts */
        get: operations["posts_recent_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/toggle-pin-status/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Toggle pinned post status */
        post: operations["posts_toggle_pin_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/can-pin/{post_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check if user can pin post with given id */
        get: operations["subscribe_can_pin_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel user`s subscription */
        post: operations["subscribe_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description History of changes of user`s subscription */
        get: operations["subscribe_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/my-pinned-post/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve, update and delete of user`s pinned post */
        get: operations["subscribe_my_pinned_post_retrieve"];
        /** @description Retrieve, update and delete of user`s pinned post */
        put: operations["subscribe_my_pinned_post_update"];
        post?: never;
        /** @description Retrieve, update and delete of user`s pinned post */
        delete: operations["subscribe_my_pinned_post_destroy"];
        options?: never;
        head?: never;
        /** @description Retrieve, update and delete of user`s pinned post */
        patch: operations["subscribe_my_pinned_post_partial_update"];
        trace?: never;
    };
    "/api/v1/subscribe/my-subscription/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Info of current user's subscription */
        get: operations["subscribe_my_subscription_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/pinned-posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieves list of all pinned posts */
        get: operations["subscribe_pinned_posts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List of available subscription plans */
        get: operations["subscribe_plans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detail info of available subscription plan */
        get: operations["subscribe_plans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscribe/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns current user's subscription status */
        get: operations["subscribe_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `created` - Created
         *     * `activated` - Activated
         *     * `renewed` - Renewed
         *     * `cancelled` - Cancelled
         *     * `expired` - Expired
         *     * `failed` - Failed
         * @enum {string}
         */
        ActionEnum: "created" | "activated" | "renewed" | "cancelled" | "expired" | "failed";
        /** @description Serializer for correct display of author info in OpenAPI. */
        AuthorInfo: {
            /** Format: uuid */
            readonly id?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            readonly full_name?: string;
            /**
             * Аватар
             * Format: uri
             */
            avatar?: string | null;
        };
        /** @description Serializer for Category */
        Category: {
            readonly id?: number;
            name: string;
            readonly slug?: string;
            description?: string;
            /** Format: date-time */
            readonly created?: string;
            readonly posts_count?: number;
        };
        /** @description Serializer for correct display of category info in OpenAPI. */
        CategoryInfo: {
            readonly id?: number;
            name: string;
            slug?: string;
        };
        /** @description Serializer for changing password */
        ChangePassword: {
            old_password: string;
            new_password: string;
            new_password_confirmation: string;
        };
        /** @description Base serializer for Comments */
        Comment: {
            readonly id?: number;
            readonly post?: string;
            content: string;
            /** Format: uuid */
            readonly author?: string;
            readonly author_info?: components["schemas"]["AuthorInfo"];
            parent?: number | null;
            readonly is_active?: boolean;
            readonly is_reply?: boolean;
            readonly replies_count?: number;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            modified?: string | null;
        };
        /** @description Serializer for Comments creation */
        CommentCreate: {
            post_id: number;
            parent?: number | null;
            content: string;
        };
        /** @description Detail serializer for Comments with responses */
        CommentDetail: {
            readonly id?: number;
            readonly post?: string;
            content: string;
            /** Format: uuid */
            readonly author?: string;
            readonly author_info?: components["schemas"]["AuthorInfo"];
            parent?: number | null;
            readonly is_active?: boolean;
            readonly is_reply?: boolean;
            readonly replies_count?: number;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            modified?: string | null;
            readonly replies?: components["schemas"]["Comment"][];
        };
        /** @description Serializer for correct display of comment_replies view response data in OpenAPI. */
        CommentReplies: {
            readonly parent_comment?: components["schemas"]["Comment"];
            readonly replies?: components["schemas"]["Comment"][];
            readonly replies_count?: number;
        };
        /** @description Serializer for Comments update */
        CommentUpdate: {
            content: string;
        };
        /** @description Serializer for correct display of created_by_info field in OpenAPI. */
        CreatedByInfo: {
            /** Format: uuid */
            readonly id?: string;
            readonly username?: string;
        };
        /** @description Serializer for correct display of featured_posts view response data in OpenAPI. */
        FeaturedPosts: {
            readonly pinned?: components["schemas"]["PostList"][];
            readonly popular?: components["schemas"]["PostList"][];
            readonly total_pinned?: number;
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedCommentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Comment"][];
        };
        PaginatedPaymentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Payment"][];
        };
        PaginatedPostListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PostList"][];
        };
        PaginatedRefundList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Refund"][];
        };
        PaginatedSubscriptionHistoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubscriptionHistory"][];
        };
        PaginatedSubscriptionPlanList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubscriptionPlan"][];
        };
        /** @description Serializer for Category */
        PatchedCategory: {
            readonly id?: number;
            name?: string;
            readonly slug?: string;
            description?: string;
            /** Format: date-time */
            readonly created?: string;
            readonly posts_count?: number;
        };
        /** @description Serializer for changing password */
        PatchedChangePassword: {
            old_password?: string;
            new_password?: string;
            new_password_confirmation?: string;
        };
        /** @description Serializer for Comments update */
        PatchedCommentUpdate: {
            content?: string;
        };
        /** @description Serializer for pinned posts */
        PatchedPinnedPost: {
            readonly id?: number;
            post?: number;
            readonly post_info?: components["schemas"]["PostInfo"];
            /** Format: date-time */
            readonly pinned_at?: string;
        };
        /** @description Serializer for creating and updating posts */
        PatchedPostCreateUpdate: {
            readonly id?: number;
            title?: string;
            readonly slug?: string;
            content?: string;
            /** Format: uri */
            image?: string | null;
            category?: number | null;
            publication_status?: components["schemas"]["PublicationStatusEnum"];
        };
        /** @description Serializer for updating user profile */
        PatchedUserUpdate: {
            /** Имя */
            first_name?: string;
            /** Фамилия */
            last_name?: string;
            /**
             * Аватар
             * Format: uri
             */
            avatar?: string | null;
            /** О себе */
            bio?: string;
        };
        /** @description Serializer for Payments */
        Payment: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly user?: string;
            readonly user_info?: components["schemas"]["UserInfo"];
            /** Format: uuid */
            subscription?: string | null;
            readonly subscription_info?: components["schemas"]["SubscriptionInfo"];
            description?: string;
            /** Format: decimal */
            amount: string;
            currency?: string;
            readonly status?: components["schemas"]["PaymentStatusEnum"];
            payment_method?: components["schemas"]["PaymentMethodEnum"];
            /** @description Check if payment is pending */
            readonly is_pending?: boolean;
            /** @description Check if payment is successful */
            readonly is_successful?: boolean;
            /** @description Check if payment can be refunded */
            readonly can_be_refunded?: boolean;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string | null;
            /** Format: date-time */
            readonly processed_at?: string | null;
        };
        /** @description Serializer for correct display of payment_analytics view response data in OpenAPI. */
        PaymentAnalytics: {
            readonly total_payments?: number;
            readonly successful_payments?: number;
            /** Format: decimal */
            readonly success_rate?: string;
            /** Format: decimal */
            readonly total_revenue?: string;
            /** Format: decimal */
            readonly monthly_revenue?: string;
            readonly monthly_payments?: number;
            /** Format: decimal */
            readonly avg_payment?: string;
            readonly active_subscriptions?: number;
            readonly period?: {
                [key: string]: string;
            };
        };
        /** @description Serializer for Payment creation */
        PaymentCreate: {
            subscription_plan_id: number;
            /** @default stripe */
            payment_method: components["schemas"]["PaymentMethodEnum"];
            /** Format: uri */
            success_url?: string;
            /** Format: uri */
            cancel_url?: string;
        };
        /** @description Serializer for correct display of subscription_info field in OpenAPI. */
        PaymentInfo: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: decimal */
            readonly amount?: string;
            readonly currency?: string;
            readonly status?: components["schemas"]["PaymentStatusEnum"];
            readonly user?: string;
        };
        /**
         * @description * `stripe` - Stripe
         *     * `paypal` - PayPal
         *     * `manual` - Manual
         * @enum {string}
         */
        PaymentMethodEnum: "stripe" | "paypal" | "manual";
        /** @description Serializer for Payment Status */
        PaymentStatus: {
            payment_id: number;
            status: components["schemas"]["PaymentStatusEnum"];
            message: string;
            /** @default false */
            subscription_activated: boolean;
        };
        /**
         * @description * `pending` - Pending
         *     * `processing` - Processing
         *     * `succeeded` - Succeeded
         *     * `cancelled` - Cancelled
         *     * `failed` - Failed
         *     * `refunded` - Refunded
         * @enum {string}
         */
        PaymentStatusEnum: "pending" | "processing" | "succeeded" | "cancelled" | "failed" | "refunded";
        /** @description Serializer for correct display of pin info in OpenAPI. */
        PinInfo: {
            readonly pinned_by?: components["schemas"]["PinnedBy"];
            /** Format: date-time */
            readonly pinned_at?: string;
        };
        /** @description Serializer for correct display of pinned by info in OpenAPI. */
        PinnedBy: {
            /** Format: uuid */
            readonly id?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            readonly has_active_subscription?: boolean;
        };
        /** @description Serializer for pinned posts */
        PinnedPost: {
            readonly id?: number;
            post: number;
            readonly post_info?: components["schemas"]["PostInfo"];
            /** Format: date-time */
            readonly pinned_at?: string;
        };
        /** @description Serializer for correct display of pinned post data in OpenAPI. */
        PinnedPostData: {
            readonly id?: number;
            title: string;
            slug?: string;
            content: string;
            /** Format: uri */
            image?: string | null;
            views_count?: number;
            /** Format: date-time */
            readonly created?: string;
            readonly category?: string;
            readonly author?: components["schemas"]["AuthorInfo"];
            readonly comments_count?: number;
            /** Format: date-time */
            readonly pinned_at?: string;
            /** @description Check if post is pinned */
            readonly is_pinned?: boolean;
        };
        /** @description Serializer for correct display of pinned_posts_list view response data in OpenAPI. */
        PinnedPostsList: {
            readonly count?: number;
            readonly results?: components["schemas"]["PinnedPostData"][];
        };
        /** @description Serializer for correct display of pinned_posts view response data in OpenAPI. */
        PinnedPostsOnly: {
            readonly count?: number;
            readonly results?: components["schemas"]["PostList"][];
        };
        /** @description Serializer for correct display of post_comments view response data in OpenAPI. */
        PostComments: {
            readonly post?: components["schemas"]["PostData"];
            readonly comments?: components["schemas"]["Comment"][];
            readonly comments_count?: number;
        };
        /** @description Serializer for creating and updating posts */
        PostCreateUpdate: {
            readonly id?: number;
            title: string;
            readonly slug?: string;
            content: string;
            /** Format: uri */
            image?: string | null;
            category?: number | null;
            publication_status?: components["schemas"]["PublicationStatusEnum"];
        };
        /** @description Serializer for correct display of post data in OpenAPI. */
        PostData: {
            readonly id?: number;
            readonly title?: string;
            readonly slug?: string;
        };
        /** @description Serializer for Post details */
        PostDetail: {
            readonly id?: number;
            title: string;
            readonly slug?: string;
            content: string;
            /** Format: uri */
            image?: string | null;
            /** Format: uuid */
            readonly author?: string;
            category?: number | null;
            publication_status?: components["schemas"]["PublicationStatusEnum"];
            readonly comments_count?: number;
            readonly views_count?: number;
            /** @description Check if post is pinned */
            readonly is_pinned?: boolean;
            readonly pinned_info?: components["schemas"]["PinInfo"];
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            modified?: string | null;
            readonly author_info?: components["schemas"]["AuthorInfo"];
            readonly category_info?: components["schemas"]["CategoryInfo"];
            /** @description Returns can post be pinned by user or not */
            readonly can_pin?: boolean;
        };
        /** @description Serializer for correct display of post info in OpenAPI. */
        PostInfo: {
            readonly id?: number;
            title: string;
            slug?: string;
            content: string;
            /** Format: uri */
            image?: string | null;
            views_count?: number;
            /** Format: date-time */
            readonly created?: string;
        };
        /** @description Serializer for list of Posts */
        PostList: {
            readonly id?: number;
            title: string;
            readonly slug?: string;
            content: string;
            /** Format: uri */
            image?: string | null;
            readonly author?: string;
            readonly category?: string;
            publication_status?: components["schemas"]["PublicationStatusEnum"];
            readonly comments_count?: number;
            readonly views_count?: number;
            /** @description Check if post is pinned */
            readonly is_pinned?: boolean;
            readonly pinned_info?: components["schemas"]["PinInfo"];
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            modified?: string | null;
        };
        /** @description Serializer for correct display of posts_by_category view response data in OpenAPI. */
        PostsByCategory: {
            readonly category?: components["schemas"]["Category"];
            readonly posts?: components["schemas"]["PostList"][];
            readonly pinned_posts_count?: number;
        };
        /**
         * @description * `d` - Draft
         *     * `p` - Published
         * @enum {string}
         */
        PublicationStatusEnum: "d" | "p";
        /** @description Serializer for correct refresh token display in OpenAPI. */
        RefreshToken: {
            refresh_token: string;
        };
        /** @description Serializer for Refund */
        Refund: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            payment: string;
            readonly payment_info?: components["schemas"]["PaymentInfo"];
            /** Format: decimal */
            amount: string;
            reason?: string;
            readonly status?: components["schemas"]["RefundStatusEnum"];
            /** @description Check if refund is partial */
            readonly is_partial?: boolean;
            /** Format: uuid */
            created_by?: string | null;
            readonly created_by_info?: components["schemas"]["CreatedByInfo"];
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly processed_at?: string | null;
        };
        /** @description Serializer for Refund creation */
        RefundCreate: {
            /** Format: decimal */
            amount: string;
            reason?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `succeeded` - Succeeded
         *     * `cancelled` - Cancelled
         *     * `failed` - Failed
         * @enum {string}
         */
        RefundStatusEnum: "pending" | "succeeded" | "cancelled" | "failed";
        /** @description Serializer for Stripe Checkout Session */
        StripeCheckoutSession: {
            /** Format: uri */
            readonly checkout_url?: string;
            readonly session_id?: number;
            readonly payment_id?: number;
        };
        /** @description Serializer for Subscriptions */
        Subscription: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly user?: string;
            readonly user_info?: components["schemas"]["AuthorInfo"];
            plan: number;
            readonly plan_info?: components["schemas"]["SubscriptionPlan"];
            readonly status?: components["schemas"]["SubscriptionStatusEnum"];
            /** Format: date-time */
            readonly start_date?: string;
            /** Format: date-time */
            readonly end_date?: string;
            /** @description Returns number of days before subscription ending */
            readonly days_remaining?: number;
            auto_renew?: boolean;
            /** @description Check if subscription is active */
            readonly is_active?: boolean;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string | null;
        };
        /** @description Serializer for subscription history */
        SubscriptionHistory: {
            readonly id?: number;
            action: components["schemas"]["ActionEnum"];
            description?: string;
            metadata?: unknown;
            /** Format: date-time */
            readonly created?: string;
        };
        /** @description Serializer for correct display of subscription_info field in OpenAPI. */
        SubscriptionInfo: {
            /** Format: uuid */
            readonly id?: string;
            readonly plan_name?: string;
            /** Format: date-time */
            readonly start_date?: string;
            /** Format: date-time */
            readonly end_date?: string;
            readonly status?: components["schemas"]["SubscriptionStatusEnum"];
        };
        /** @description Serializer for Subscription Plans */
        SubscriptionPlan: {
            readonly id?: number;
            name: string;
            /** Format: decimal */
            price: string;
            duration_days?: number;
            /** @description List of subscription plan's features */
            features?: unknown;
            is_active?: boolean;
            /** Format: date-time */
            readonly created?: string;
        };
        /**
         * @description * `active` - Active
         *     * `expired` - Expired
         *     * `cancelled` - Canceled
         *     * `pending` - Pending
         * @enum {string}
         */
        SubscriptionStatusEnum: "active" | "expired" | "cancelled" | "pending";
        /** @description Serializer for correct display of toggle_post_pin_status view response data in OpenAPI. */
        TogglePostPinStatus: {
            readonly msg?: string;
            readonly is_pinned?: boolean;
            readonly post?: components["schemas"]["PostDetail"];
        };
        TokenRefresh: {
            readonly access?: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        /** @description Serializer for correct display of user_info field in OpenAPI. */
        UserInfo: {
            /** Format: uuid */
            readonly id?: string;
            readonly username?: string;
            /** Format: email */
            readonly email?: string;
        };
        /** @description Serializer for user logging in */
        UserLogin: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Serializer for correct display of user_payment_history view response data in OpenAPI. */
        UserPaymentHistory: {
            readonly count?: number;
            readonly results?: components["schemas"]["Payment"][];
        };
        /** @description Serializer for user profile */
        UserProfile: {
            /** Format: uuid */
            readonly id?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            /** Имя */
            first_name?: string;
            /** Фамилия */
            last_name?: string;
            readonly full_name?: string;
            /**
             * Аватар
             * Format: uri
             */
            avatar?: string | null;
            /** О себе */
            bio?: string;
            readonly posts_count?: number;
            readonly comments_count?: number;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string | null;
        };
        /** @description Serializer for registering new users */
        UserRegistration: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
            /** Имя */
            first_name?: string;
            /** Фамилия */
            last_name?: string;
        };
        /** @description Serializer for correct user registration/login response display in OpenAPI. */
        UserRegistrationLoginResponse: {
            user: components["schemas"]["UserProfile"];
            refresh: string;
            access: string;
            msg: string;
        };
        /** @description Serializer for user subscription status */
        UserSubscriptionStatus: {
            has_subscription: boolean;
            is_active: boolean;
            can_pin_posts: boolean;
            subscription: components["schemas"]["Subscription"] | null;
            pinned_post: components["schemas"]["PinnedPost"] | null;
        };
        /** @description Serializer for updating user profile */
        UserUpdate: {
            /** Имя */
            first_name?: string;
            /** Фамилия */
            last_name?: string;
            /**
             * Аватар
             * Format: uri
             */
            avatar?: string | null;
            /** О себе */
            bio?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_change_password_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePassword"];
                };
            };
        };
    };
    auth_change_password_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChangePassword"];
                "multipart/form-data": components["schemas"]["PatchedChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChangePassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePassword"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
                "multipart/form-data": components["schemas"]["UserLogin"];
                "application/x-www-form-urlencoded": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistrationLoginResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshToken"];
                "multipart/form-data": components["schemas"]["RefreshToken"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshToken"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Logged out successfully. */
                        msg?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid token. */
                        error?: string;
                    };
                };
            };
        };
    };
    auth_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    auth_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
                "multipart/form-data": components["schemas"]["UserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
        };
    };
    auth_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistration"];
                "multipart/form-data": components["schemas"]["UserRegistration"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistrationLoginResponse"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    comments_list: {
        parameters: {
            query?: {
                author?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                parent?: number;
                post_id?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCommentList"];
                };
            };
        };
    };
    comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
                "multipart/form-data": components["schemas"]["CommentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
        };
    };
    comments_replies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentReplies"];
                };
            };
        };
    };
    comments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentDetail"];
                };
            };
        };
    };
    comments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
                "multipart/form-data": components["schemas"]["CommentUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUpdate"];
                };
            };
        };
    };
    comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    comments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCommentUpdate"];
                "multipart/form-data": components["schemas"]["PatchedCommentUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCommentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUpdate"];
                };
            };
        };
    };
    comments_my_comments_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                parent?: number;
                post?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCommentList"];
                };
            };
        };
    };
    comments_post_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostComments"];
                };
            };
        };
    };
    docs_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    payments_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentList"];
                };
            };
        };
    };
    payments_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    payments_refund_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundCreate"];
                "multipart/form-data": components["schemas"]["RefundCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["RefundCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    payments_retry_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCheckoutSession"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    payments_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    payments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payments_analytics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAnalytics"];
                };
            };
        };
    };
    payments_create_checkout_session_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
                "multipart/form-data": components["schemas"]["PaymentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCheckoutSession"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    payments_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPaymentHistory"];
                };
            };
        };
    };
    payments_refunds_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRefundList"];
                };
            };
        };
    };
    payments_refunds_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    posts_list: {
        parameters: {
            query?: {
                category?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /**
                 * @description * `d` - Draft
                 *     * `p` - Published
                 */
                publication_status?: "d" | "p";
                /** @description A search term. */
                search?: string;
                title?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostListList"];
                };
            };
        };
    };
    posts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateUpdate"];
                "multipart/form-data": components["schemas"]["PostCreateUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PostCreateUpdate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCreateUpdate"];
                };
            };
        };
    };
    posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
        };
    };
    posts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateUpdate"];
                "multipart/form-data": components["schemas"]["PostCreateUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PostCreateUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCreateUpdate"];
                };
            };
        };
    };
    posts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPostCreateUpdate"];
                "multipart/form-data": components["schemas"]["PatchedPostCreateUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPostCreateUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCreateUpdate"];
                };
            };
        };
    };
    posts_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    posts_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    posts_categories_posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostsByCategory"];
                };
            };
        };
    };
    posts_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    posts_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    posts_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    posts_featured_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedPosts"];
                };
            };
        };
    };
    posts_my_posts_list: {
        parameters: {
            query?: {
                category?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /**
                 * @description * `d` - Draft
                 *     * `p` - Published
                 */
                publication_status?: "d" | "p";
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPostListList"];
                };
            };
        };
    };
    posts_pinned_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedPostsOnly"];
                };
            };
        };
    };
    posts_popular_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"][];
                };
            };
        };
    };
    posts_recent_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"][];
                };
            };
        };
    };
    posts_toggle_pin_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TogglePostPinStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    subscribe_can_pin_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        post_id?: number;
                        can_pin?: boolean;
                        checks?: Record<string, never>;
                        /** @example Can pin post. */
                        msg?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        post_id?: number;
                        can_pin?: boolean;
                        checks?: {
                            post_exists?: boolean;
                        };
                        /** @example Post not found. */
                        msg?: string;
                    };
                };
            };
        };
    };
    subscribe_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Subscription cancelled successfully. */
                        msg?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example No active subscription found. */
                        error?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Subscription not found. */
                        error?: string;
                    };
                };
            };
        };
    };
    subscribe_history_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubscriptionHistoryList"];
                };
            };
        };
    };
    subscribe_my_pinned_post_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedPost"];
                };
            };
        };
    };
    subscribe_my_pinned_post_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinnedPost"];
                "multipart/form-data": components["schemas"]["PinnedPost"];
                "application/x-www-form-urlencoded": components["schemas"]["PinnedPost"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedPost"];
                };
            };
        };
    };
    subscribe_my_pinned_post_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribe_my_pinned_post_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPinnedPost"];
                "multipart/form-data": components["schemas"]["PatchedPinnedPost"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPinnedPost"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedPost"];
                };
            };
        };
    };
    subscribe_my_subscription_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
        };
    };
    subscribe_pinned_posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedPostsList"];
                };
            };
        };
    };
    subscribe_plans_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubscriptionPlanList"];
                };
            };
        };
    };
    subscribe_plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlan"];
                };
            };
        };
    };
    subscribe_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSubscriptionStatus"];
                };
            };
        };
    };
}
