# Generated by Django 5.2.7 on 2025-11-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("activated", "Activated"),
                    ("renewed", "Renewed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
